import { GetServerSidePropsContext } from 'next'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Company Name</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}

export const getServerSideProps = async (
  context: GetServerSidePropsContext,
) => {
  return {
    redirect: {
      destination: `/materials`,
      permanent: false,
    },
    props: {},
  }
}
