import Head from 'next/head'
import { trpc } from '../utils/trpc'

export default function Home() {
  const { data:sectors } = trpc.resources.getSectorsList.useQuery(null, {
    refetchInterval: 3000,
  })

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ul>{}</ul>
    </div>
  )
}
