import {
  Activity,
  AlertCircle,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  Clock4,
  Copy,
  CornerUpLeft,
  CornerUpRight,
  File,
  FileText,
  Folders,
  Github,
  HelpCircle,
  Icon as LucideIcon,
  Info,
  List,
  Loader2,
  Maximize,
  Menu,
  Minimize,
  PauseCircle,
  Pizza,
  Plus,
  RefreshCw,
  Repeat,
  Rocket,
  Settings,
  Timer,
  Trash,
  User,
  Users,
  X,
  XCircle,
} from 'lucide-react'

export type Icon = LucideIcon

const Icons = {
  spinner: Loader2,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronDown: ChevronDown,
  trash: Trash,
  post: FileText,
  page: File,
  settings: Settings,
  user: User,
  users: Users,
  info: Info,
  help: HelpCircle,
  pizza: Pizza,
  github: Github,
  error: AlertCircle,
  check: CheckCircle,
  clock: Clock4,
  activity: Activity,
  timer: Timer,
  pause: PauseCircle,
  list: List,
  cornerUpRight: CornerUpRight,
  retry: Repeat,
  maximize: Maximize,
  minimize: Minimize,
  refresh: RefreshCw,
  copy: Copy,
  cornerUpLeft: CornerUpLeft,
  rocket: Rocket,
  menu: Menu,
  x: X,
  xCircle: XCircle,
  folders: Folders,
  plus: Plus,
}

export type IconName = keyof typeof Icons

export default Icons
